import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:mad_test_work/src/camera_feature/domain/place/photo_point.dart';
import 'package:mad_test_work/src/camera_feature/domain/place/place.dart';
// required: associates our `main.dart` with the code generated by Freezed
part 'place_model.freezed.dart';

@freezed
class PlaceModel with _$PlaceModel {
  const factory PlaceModel(
    Place place,
  ) = _PlaceModel;

  factory PlaceModel.fromJson(Map<String, dynamic> json) {
    final String title = json.containsKey('title') && json['title'] is String
        ? json['title']
        : ' Error here!';
    final int totalPoints = json.containsKey('total_points_count') &&
            json['total_points_count'] is int
        ? json['total_points_count']
        : 0;
    final int remainingPoints =
        json.containsKey('remaining_points') && json['remaining_points'] is int
            ? json['remaining_points']
            : 0;
    final List<Map<String, dynamic>> points = json.containsKey('points') &&
            json['points'] is List<Map<String, dynamic>>
        ? json['points']
        : [];
    final decodedPoints = points.map((e) => PhotoPoint.fromJson(e)).toList();
    final place = Place(
      title: title,
      totalPoints: totalPoints,
      remainingPoints: remainingPoints,
      points: decodedPoints,
    );
    return PlaceModel(place);
  }
}
