// Mocks generated by Mockito 5.4.4 from annotations
// in mad_test_work/test/camera_feature/bloc/places_list_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:dartz/dartz.dart' as _i3;
import 'package:mad_test_work/core/failtures/failures.dart' as _i7;
import 'package:mad_test_work/core/utils/place_name_filter.dart' as _i8;
import 'package:mad_test_work/src/camera_feature/domain/place/place.dart'
    as _i9;
import 'package:mad_test_work/src/camera_feature/domain/place/place_model.dart'
    as _i6;
import 'package:mad_test_work/src/camera_feature/domain/repository/places_repository_interface.dart'
    as _i2;
import 'package:mad_test_work/src/camera_feature/domain/use_cases/get_places_use_case.dart'
    as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeIPlacesRepository_0 extends _i1.SmartFake
    implements _i2.IPlacesRepository {
  _FakeIPlacesRepository_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeEither_1<L, R> extends _i1.SmartFake implements _i3.Either<L, R> {
  _FakeEither_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [GetPlacesUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetPlacesUseCase extends _i1.Mock implements _i4.GetPlacesUseCase {
  MockGetPlacesUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.IPlacesRepository get placesRepository => (super.noSuchMethod(
        Invocation.getter(#placesRepository),
        returnValue: _FakeIPlacesRepository_0(
          this,
          Invocation.getter(#placesRepository),
        ),
      ) as _i2.IPlacesRepository);

  @override
  _i5.Future<_i3.Either<List<_i6.PlaceModel>, _i7.Failure>> getPlaces() =>
      (super.noSuchMethod(
        Invocation.method(
          #getPlaces,
          [],
        ),
        returnValue:
            _i5.Future<_i3.Either<List<_i6.PlaceModel>, _i7.Failure>>.value(
                _FakeEither_1<List<_i6.PlaceModel>, _i7.Failure>(
          this,
          Invocation.method(
            #getPlaces,
            [],
          ),
        )),
      ) as _i5.Future<_i3.Either<List<_i6.PlaceModel>, _i7.Failure>>);
}

/// A class which mocks [PlaceNameFilter].
///
/// See the documentation for Mockito's code generation for more information.
class MockPlaceNameFilter extends _i1.Mock implements _i8.PlaceNameFilter {
  MockPlaceNameFilter() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i9.Place> filteredPlaces(
    List<_i9.Place>? places,
    String? filterString,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #filteredPlaces,
          [
            places,
            filterString,
          ],
        ),
        returnValue: <_i9.Place>[],
      ) as List<_i9.Place>);
}
